
export interface AccountI {
  id: string;
  pid: string; // user's personal id
  userId: string; // owner id
  cardCode: string;
  accountNumber: string; // (is autogenerated, like id)
  balance: number|0;
}

export interface ServiceI {
  id: string;
  name: string;
  type: string;
}

export interface TransactionI {
  id: string;
  senderId: string; // id of sender 
  senderAccountId: string; // sender account id
  reciverId: string;
  reciverAccountId: string;
  amount: number; // transferred money
  date: Date|string;
}

export interface PaymentI {
  id: string;
  senderId: string; // id of sender 
  senderAccountId: string; // sender account id
  serviceId: string;
  serviceName: string;
  amount: number // transferred money
  date: Date;
}

export interface UserI {
  id: string;
  name: string;
  password: string;
  pid: string; //"20001040500"; // personal id
  accounts: AccountI[]; // array of account ids
  transactions: TransactionI[];
  servicePayments: ServiceI[];
}

export interface BankOperatorI {
  id: string;
  name: string;
  password: string;
  isOperator: boolean;
}